services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "${CLIENT_PORT}:5173"
    depends_on:
      - server
    environment:
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
    
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "${SERVER_PORT}:8383"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${SERVER_PORT}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: echoboardDB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
